# Generated by Django 4.1 on 2022-08-27 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scrape", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editedfield",
            name="iplist_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="scrape.iplist"
            ),
        ),
    ]
