# Generated by Django 3.2.5 on 2022-08-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
