# Generated by Django 3.2.5 on 2022-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='anonymity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='iplist',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='iplist',
            name='port',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='iplist',
            name='protocol',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
