# Generated by Django 3.2.5 on 2022-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_auto_20220828_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='ipadress',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
