# Generated by Django 3.2.5 on 2022-08-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_alter_iplist_ipadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplist',
            name='ipadress',
            field=models.CharField(max_length=20),
        ),
    ]
