# Generated by Django 3.2.13 on 2022-08-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0008_alter_iplist_ipadress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditedField',
        ),
    ]
